export const COMPLAINTS_FETCH_PENDING = "COMPLAINTS_FETCH_PENDING";
export const COMPLAINTS_FETCH_COMPLETE = "COMPLAINTS_FETCH_COMPLETE";
export const COMPLAINTS_FETCH_ERROR = "COMPLAINTS_FETCH_ERROR";
export const COMPLAINTS_CATEGORIES_FETCH_SUCCESS = "COMPLAINTS_CATEGORIES_FETCH_SUCCESS";
export const COMPLAINTS_CATEGORIES_FETCH_ERROR = "COMPLAINTS_CATEGORIES_FETCH_ERROR";
export const COMPLAINTS_SORT_ORDER = "COMPLAINTS_SORT_ORDER";
export const COMPLAINTS_SEND_MESSAGE = "COMPLAINTS_SEND_MESSAGE";
export const COMPLAINTS_SEND_MESSAGE_SHAREMEDIA = "COMPLAINTS_SEND_MESSAGE_SHAREMEDIA";
export const COMPLAINTS_SEND_MESSAGE_SHARECONTENT_TO = "COMPLAINTS_SEND_MESSAGE_SHARECONTENT_TO";
export const COMPLAINTS_DEPARTMENT_FETCH_SUCCESS = "COMPLAINTS_DEPARTMENT_FETCH_SUCCESS";
export const COMPLAINTS_DEPARTMENT_FETCH_ERROR = "COMPLAINTS_DEPARTMENT_FETCH_ERROR";
export const COMPLAINTS_SECTOR_FETCH_SUCCESS = "COMPLAINTS_SECTOR_FETCH_SUCCESS";
export const COMPLAINTS_SECTOR_FETCH_ERROR = "COMPLAINTS_SECTOR_FETCH_ERROR";

export const PAYMENT_FETCH_COMPLETE = "PAYMENT_FETCH_COMPLETE";
export const HISTORY_FETCH_COMPLETE="HISTORY_FETCH_COMPLETE";
export const APPLICATION_FETCH_COMPLETE="APPLICATION_FETCH_COMPLETE";

export const APPLICATION_FETCH_ERROR="APPLICATION_FETCH_ERROR"
export const HISTORY_FETCH_ERROR="HISTORY_FETCH_ERROR"
export const PAYMENT_FETCH_ERROR="PAYMENT_FETCH_ERROR"

export const AFTER_PAYMENT_FETCH_DETAILS="AFTER_PAYMENT_FETCH_DETAILS"
export const AFTER_PAYMENT_FETCH_ERROR="AFTER_PAYMENT_FETCH_ERROR"

export const DOWNLOAD_RECEIPT_COMPLETE="DOWNLOAD_RECEIPT_COMPLETE"
export const DOWNLOAD_RECEIPT_ERROR="DOWNLOAD_RECEIPT_ERROR"

export const DOWNLOAD_APPLICATION_ERROR="DOWNLOAD_APPLICATION_ERROR"
export const DOWNLOAD_APPLICATION_COMPLETE="DOWNLOAD_APPLICATION_COMPLETE"

export const DOWNLOAD_LETTER_COMPLETE="DOWNLOAD_LETTER_COMPLETE"
export const DOWNLOAD_LETTER_ERROR="DOWNLOAD_LETTER_ERROR"

export const CREATE_WATER_TANKER_COMPLETE="CREATE_WATER_TANKER_COMPLETE"
export const CREATE_WATER_ERROR="CREATE_WATER_ERROR"


export const APPLICATION_SECTOR_FETCH_ERROR = "APPLICATION_SECTOR_FETCH_ERROR";
export const APPLICATION_SECTOR_FETCH_SUCCESS = "APPLICATION_SECTOR_FETCH_SUCCESS";

export const APPLICATION_TYPE_FETCH_SUCCESS="APPLICATION_TYPE_FETCH_SUCCESS"

export const DOWNLOAD_BWT_APPLICATION_COMPLETE="DOWNLOAD_BWT_APPLICATION_COMPLETE"
export const DOWNLOAD_BWT_APPLICATION_ERROR="DOWNLOAD_BWT_APPLICATION_ERROR"



export const MCCAPPLICATION_FETCH_COMPLETE="MCCAPPLICATION_FETCH_COMPLETE"
export const MCCAPPLICATION_FETCH_ERROR="MCCAPPLICATION_FETCH_ERROR"